services:
  postgres:
    image: 'pgvector/pgvector:pg17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE}'
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    volumes:
      - ./mailpit-data:/data
    environment:
      - MP_MAX_MESSAGES=500
      - MP_DATABASE=/data/mailpit.db
  adminer:
    image: 'adminer:latest'
    ports:
      - '${FORWARD_ADMINER_PORT:-8080}:8080'
    depends_on:
      - postgres
